### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by SardharaRahul** [bluesnap/bluesnap-android#1]
Hi Below I have written in my code. 

 implementation **'com.github.bluesnap:bluesnap-android-int:2.5.2'**
 
  maven { s**etUrl ("https://jitpack.io")** }
        maven { setUrl("https://maven.aliyun.com/repository/public") }
        maven {
            url 'https://maven.google.com/'
            name 'Google'
        }
        maven {
            **url  "https://cardinalcommerceprod.jfrog.io/artifactory/android"
            credentials {
                username 'bluesnap_sdk_users'
                // This is here by design:
                password 'AKCp8jXXXZXZXZZZZZZZZZZZZZXXXDKhLRmaaKiKj3pnFwu9mwzv2n' // public password.. not a secret.
            }**
        }
        mavenCentral()
    }
    
    
    but is thrown below error,
    
![Screenshot 2024-09-26 at 2 13 23 PM](https://github.com/user-attachments/assets/b26d76da-5318-42cd-a3ec-d71c39c31db9)

Please guide me on this..

**Comment by snpori** [comment]
The implementation line is refering to the old repo name.
Use something like this:
implementation 'com.github.bluesnap:bluesnap-android:v2.5.5'
